baseURL: https://raroftexas.com
languageCode: en-us
title: RAR of Texas, LLC
theme: rar-hugo
copyright: RAR of Texas
paginate: 3


markup:
  goldmark:
    renderer:
      unsafe: true
      
params:
  favicon: /logo/RAR_icon.svg
  brandlogo_dark: /logo/RAR-of-Texas_logo.svg
  description: RAR of Texas

  
menu:
    nav:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: products
      name: Products
      url: /products/
      weight: 2
    - identifier: services
      name: Services
      url: /services/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4
    - identifier: about
      name: About
      url: /about/
      weight: 5
    #- identifier: blog
    #  name: Blog
    #  url: /blog/
    #  weight: 4